### PR TITLE
Bump dqlite to support arm 32-bit

### PR DESCRIPTION
**Pull request by ibuildthecloud**
Addresses https://github.com/rancher/k3s/issues/1155

### CODE REVIEW

**Comment by alexellis** [comment]
Thank you.

What commands do I need to pass to the curl | sh script to setup a "server agent"?

**Comment by alexellis** [comment]
https://github.com/alexellis/k3sup/pull/115

This is what I went with

**Comment by alexellis** [comment]
:tada:

**Comment by davidnuzik** [comment]
Will be tested in GH issue https://github.com/rancher/k3s/issues/1115

**Pull request merged**
