### PR TITLE
contrib/ansible: Fix systemd TimeoutStartSec in contrib/ansible

### PR DESCRIPTION
**Pull request by St0rmingBr4in**
This fixes the issue #360 that was fixed in #365 but not inside the ansible playbook.

Signed-off-by: Julien DOCHE <julien.doche@gmail.com>

### CODE REVIEW

**Comment by St0rmingBr4in** [comment]
@erikwilson Could you take a look please ? :)

**Comment by erikwilson** [comment]
Thanks for the PR @St0rmingBr4in!

Change looks good, is just updating to what is the currently the root of the repo. 

Sorry for the ansible PRs piling up, I am working on getting the ansible stuff moved to another repo, would you be interested in helping to review & merge PRs?

**Comment by St0rmingBr4in** [comment]
Yeah sure I would be interested 😊

**Comment by erikwilson** [comment]
Awesome, have created a repo and copied the commits to https://github.com/rancher/k3s-ansible, do you mind closing these PRs and re-creating them there? 

Have also added access for @itwars as the original creator of the ansible contrib stuff. If you two are able to help get things moving there is would be greatly appreciated, many thanks!

**Comment by itwars** [comment]
Excellent @erikwilson !

**Comment by St0rmingBr4in** [comment]
Yep, I'll move and close those PR 😛 Thank you

**Pull request closed without merging**
