### PR TITLE
contrib/ansible: Fixes 'search' test usage syntax

### PR DESCRIPTION
**Pull request by tamsky**
existing usage produced an error under ansible 2.6.1

### CODE REVIEW

**Comment by erikwilson** [comment]
Thanks for the contributions @tamsky !
@itwars would you be able to review this PR and the other ansible PRs?

**Comment by itwars** [comment]
Sure! I’ll take time this week-end

**Comment by itwars** [comment]
Good to go!

**Comment by erikwilson** [comment]
Thanks @itwars & @tamsky! I am not sure if there is a good way to filter notifications to that fine of a level with github. Personally I use lots of gmail filters to try to send relevant github notification to my inbox rather than a different folder.

**Pull request merged**
