### PR TITLE
Agent flag to allow connect to a server behind NAT

### LINKED ISSUE #819: Over Internet Setup
Hello, 

I have been trying to setup a working cluster using k3s for the last couple of days.
Right now, all system pod are Running, all services have endpoint, coredns is working.

However, inter host is not, thus pods on host not running coredns are unable to do `nslookup google.fr`

At the moment, I am trying to run the cluster over the internet : master node is in the cloud, some worker are in other clouds and some are at home ( behind a NAT ) .
All those node are in Ready state and able to run pods, so issue seems more likely to be on flannel setup I guess...
Is there anything I can do to investigate a bit more and make it work ( already been through k8s network debug guide without success ) ?

Regards,

### PR DESCRIPTION
**Pull request by bugfest**
`--server-public` agent flag - if set, allows agents to connect servers behind NAT or in a non-routable network by enforcing the use of the server's public URL/IP 

Fixes #819 without the need of adding `advertise-address` to kube-apiserver and the routing issue for agents that might be running in the internal network. 

This has been fixed on top of tag v0.9.1 as I saw a lot of changes are going on in preparation of v.1 - **DO NOT MERGE (yet)** - if you think it's a functionality that deserves to be included I can port it to v1.0 whenever is ready or more stable. 

### Log examples
Current behavior: if you try to connect a server not advertising the public IP but behind NAT: 
```
Oct 08 07:02:15 agent-ext-1 k3s[11810]: time="2019-10-08T07:02:15.172082271-04:00" level=info msg="Starting k3s agent v0.9.1 (755bd1c6)"
Oct 08 07:02:15 agent-ext-1 k3s[11810]: time="2019-10-08T07:02:15.172574695-04:00" level=info msg="Running load balancer 127.0.0.1:24220 -> [master.xxxxxx.com:6443]"
Oct 08 07:02:27 agent-ext-1 k3s[11810]: time="2019-10-08T07:02:27.431901049-04:00" level=info msg="Logging containerd to /var/lib/rancher/k3s/agent/containerd/containerd.log"
Oct 08 07:02:27 agent-ext-1 k3s[11810]: time="2019-10-08T07:02:27.432172188-04:00" level=info msg="Running containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/lib/rancher/k3s/agent/c
ontainerd"
Oct 08 07:02:27 agent-ext-1 k3s[11810]: time="2019-10-08T07:02:27.432967908-04:00" level=info msg="Waiting for containerd startup: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error wh
ile dialing dial unix /run/k3s/containerd/containerd.sock: connect: connection refused\""
Oct 08 07:02:28 agent-ext-1 k3s[11810]: time="2019-10-08T07:02:28.434819752-04:00" level=info msg="module br_netfilter was already loaded"
Oct 08 07:02:28 agent-ext-1 k3s[11810]: time="2019-10-08T07:02:28.434914644-04:00" level=info msg="module overlay was already loaded"
Oct 08 07:02:28 agent-ext-1 k3s[11810]: time="2019-10-08T07:02:28.434936381-04:00" level=info msg="module nf_conntrack was already loaded"
Oct 08 07:02:29 agent-ext-1 k3s[11810]: time="2019-10-08T07:02:29.242793413-04:00" level=info msg="Updating load balancer server addresses -> [192.168.11.27:6443 master.xxxxxx.com:6443]"
Oct 08 07:02:29 agent-ext-1 k3s[11810]: time="2019-10-08T07:02:29.244214292-04:00" level=info msg="Connecting to proxy" url="wss://192.168.11.27:6443/v1-k3s/connect"
```
As `192.168.11.27` is the private network where the server is sitting on, and is not reachable from agent-ext-1, the agent timeouts and is not able to finish the connection (is showed as `NotReady` in `kubectl`)

Patched k3s agent running with the flag enabled:
```
Oct 09 05:48:14 agent-ext-1 k3s[22411]: time="2019-10-09T05:48:14-04:00" level=info msg="Preparing data dir /var/lib/rancher/k3s/data/7850894a1c2ee3546745f3484abde3877edacd5736780c7f1f19058bc80ed527"
Oct 09 05:48:16 agent-ext-1 k3s[22411]: time="2019-10-09T05:48:16.044985875-04:00" level=info msg="Starting k3s agent 0e474fadfa (0e474fad)"
Oct 09 05:48:16 agent-ext-1 k3s[22411]: time="2019-10-09T05:48:16.045395480-04:00" level=info msg="Running load balancer 127.0.0.1:12199 -> [17.15.xx.xx:6443]"
Oct 09 05:48:28 agent-ext-1 k3s[22411]: time="2019-10-09T05:48:28.063248803-04:00" level=info msg="Logging containerd to /var/lib/rancher/k3s/agent/containerd/containerd.log"
Oct 09 05:48:28 agent-ext-1 k3s[22411]: time="2019-10-09T05:48:28.063584405-04:00" level=info msg="Running containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/lib/rancher/k3s/agent/c
Oct 09 05:48:28 agent-ext-1 k3s[22411]: time="2019-10-09T05:48:28.064688775-04:00" level=info msg="Waiting for containerd startup: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error wh
Oct 09 05:48:29 agent-ext-1 k3s[22411]: time="2019-10-09T05:48:29.069064832-04:00" level=info msg="module br_netfilter was already loaded"
Oct 09 05:48:29 agent-ext-1 k3s[22411]: time="2019-10-09T05:48:29.069391943-04:00" level=info msg="module overlay was already loaded"
Oct 09 05:48:29 agent-ext-1 k3s[22411]: time="2019-10-09T05:48:29.069455205-04:00" level=info msg="module nf_conntrack was already loaded"
Oct 09 05:48:28 agent-ext-1 k3s[22411]: time="2019-10-09T05:48:28.063248803-04:00" level=info msg="Logging containerd to /var/lib/rancher/k3s/agent/containerd/containerd.log"
Oct 09 05:48:28 agent-ext-1 k3s[22411]: time="2019-10-09T05:48:28.063584405-04:00" level=info msg="Running containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/lib/rancher/k3s/agent/c
Oct 09 05:48:28 agent-ext-1 k3s[22411]: time="2019-10-09T05:48:28.064688775-04:00" level=info msg="Waiting for containerd startup: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error wh
Oct 09 05:48:29 agent-ext-1 k3s[22411]: time="2019-10-09T05:48:29.069064832-04:00" level=info msg="module br_netfilter was already loaded"
Oct 09 05:48:29 agent-ext-1 k3s[22411]: time="2019-10-09T05:48:29.069391943-04:00" level=info msg="module overlay was already loaded"
Oct 09 05:48:29 agent-ext-1 k3s[22411]: time="2019-10-09T05:48:29.069455205-04:00" level=info msg="module nf_conntrack was already loaded"
Oct 09 05:48:29 agent-ext-1 k3s[22411]: time="2019-10-09T05:48:29.856021052-04:00" level=info msg="Server is on Public IP: [17.15.xx.xx:6443]"
Oct 09 05:48:29 agent-ext-1 k3s[22411]: time="2019-10-09T05:48:29.856632771-04:00" level=info msg="Connecting to proxy" url="wss://17.15.xx.xx:6443/v1-k3s/connect"
Oct 09 05:48:30 agent-ext-1 k3s[22411]: time="2019-10-09T05:48:30.636356903-04:00" level=warning msg="Disabling CPU quotas due to missing cpu.cfs_period_us"
Oct 09 05:48:30 agent-ext-1 k3s[22411]: time="2019-10-09T05:48:30.640318995-04:00" level=info msg="Running kubelet --address=0.0.0.0 --anonymous-auth=false --authentication-token-webhook=true --authorization-mode=Webhook --cert-dir=/var/lib/rancher/k3s/agent/kubelet/pki ...
```

### CODE REVIEW

**Comment by erikwilson** [comment]
This will break HA.

It may be better to set up the k8s endpoints to use the public ip. 
If you are actually running over an insecure public network hopefully you are using encryption for flannel also.

**Comment by bugfest** [comment]
Hi @erikwilson! 

Thanks for taking a look to this. 

I'm assuming if you run HA the servers you also need an external LB; agents running within the same subnet won't have the flag enabled and will keep working as usual. 

Before proposing these changes I considered announcing the public IP directly but that requires all the nodes have Internet access. This is not the case if you want to have some nodes in your internal network and others on a public one. 

Can you point me to some documentation or test to verify it won't interfere with HA? I'm willing to document the scenario as it wrings a lot of value for us. 

Good point on the cni encryption. I saw you're adding flannel ipsec support in v1; that's great! looking forward to use it.

**Comment by erikwilson** [comment]
Thanks! ipsec is also available for testing in the v0.10.0-alpha1 release.

The k8s endpoints are used for two purposes in the agent code:

1. Each agent connects to every master endpoint to setup a tunnel, this allows the masters to talk to agent kubelets & do things like fetch logs
2. Each agent sets up a local load balancer to the master endpoints, this allows an agent to failover to another master without the need of an external load balancer

I am hesitant to provide a flag which would break other functionality. Maybe if it were explicitly called `--no-ha` or something like to turn off the use of endpoints & lb and only use the server url. I am curious if there may be other networking things broken in a setup like this tho.

**Comment by erikwilson** [comment]
HA will not work properly with the `--no-ha` flag, I am confused why there is a diagram for that. 

A tunnel is established between each agent and every master, this flag would disable that functionality.

**Comment by erikwilson** [comment]
I think I understand what you are trying to show in the diagram, but it appears confusing if shown as a supported scenario from documentation point of view.

**Comment by erikwilson** [comment]
Another possibility we can explore is to create tunnel connections between the HA masters, so as long as an agent is connected to one master any other master would be able to use that connection. That will create extra hops for communication if not going through the original master, but would allow for a single tunnel to external lb per agent behind a NAT.

**Comment by erikwilson** [comment]
Another consideration is services that might try to talk directly to a node's kubelet, like metrics-server, would likely not be able to behind a NAT setup.

I am curious how well flannel works also, as it would probably need to do some UDP hole punching to get nodes communicating properly behind a NAT.

**Comment by bugfest** [comment]
Hi @erikwilson, thanks for your input. I'm going to review the code to see how this could be implemented and go back to you if I find more answers than questions : ) - Will close this PR and avoid bothering you with this scenario that might be just a guy's corner-case 

Thanks for your time again & congrats for this amazing piece of software

**Comment by CamelCaseNotation** [comment]
@bugfest I would like to achieve something similar to what you've done here, although with slight differences. I think I know how we can do this without breaking HA. @erikwilson basically nailed it with this comment:

> ... allow for a single tunnel to external lb per agent behind a NAT

Not _exactly_ what I had in mind, but similar. I described how I think it could work here: https://github.com/rancher/k3s/issues/986#issuecomment-547727719

**Comment by CamelCaseNotation** [comment]
The HA setup in k3s today load balances the traffic _from_ the kubelet (agent) _to_ the apiserver (master).

@bugfest Any Pods running on the worker nodes which send a request to the apiserver via the Kubernetes Service IP will not be able to reach it even with these changes. Only the kubelet would be configured to talk through the public URL. My comment linked above could be one way to solve the issue of Pods being unable to reach the apiserver via the Service ClusterIP.

As for this PR breaking HA, I think 3 things need to happen.

1) This PR should change the flag slightly such that multiple public server endpoints are accepted, exactly like the `--etcd-servers` flag of the apiserver

2) This PR should also have the public server URLs added to the `addresses` var [here](https://github.com/rancher/k3s/blob/d85a9183ae941dd4d9eb2f459d06032623fe5430/pkg/agent/tunnel/tunnel.go#L56) in the same way the original server URL is added.

Both 1 & 2 should be straightforward changes
 
3) The HA implementation should be modified to _skip over_ proxy tunnel creation if an address in `addresses` of [this function](https://github.com/rancher/k3s/blob/d85a9183ae941dd4d9eb2f459d06032623fe5430/pkg/agent/tunnel/tunnel.go#L56) is unreachable.

With those 3 items, HA will continue working as expected, but also so will the NAT use-case. A downside is there could be 2 tunnels to the same master if both the Endpoint and public URL for the apiserver is reachable.

@erikwilson thoughts?

**Comment by erikwilson** [comment]
I think for this to work well with flannel (ipsec/wireguard on different networks) it may be we need to set the flannel public ip separately (flannel.alpha.coreos.com/public-ip on node). 

The best bet is to just start with non-HA, and make sure the network is created properly through a NAT. 

I wonder if we can create special k3s endpoints to route through the flannel network for HA instead of using the kubernetes endpoints.

Also, I feel like it might be helpful to have some sort of service that makes it easier to facilitate this sort of stuff, with p2p setup being a free feature but for networks not capable of supporting NAT then maybe a premium hosted vpn like solution? Maybe something also capable of getting a quick temporary server join url that is publicly routable, or premium for custom urls, similar to ngrok?

**Comment by ndjhartman** [comment]
I'm trying to run k3s server on an AWS instance with the k3s agents running on edge devices outside of the AWS agent. I was running into this exact issue of the proxy trying to connect to the internal IP rather than the public IP.

I ported @bugfest PR to v1.17.2+k3s1 (https://github.com/ndjhartman/k3s/tree/v1.17.2+k3s1-agent-publicip) and it is achieving exactly what I need. I'm successfully able to make the connection as the proxy now connects to the public IP rather than the private.

```
Server is on Public IP: [ec2-18-221-152-110.us-east-2.compute.amazonaws.com:873] 
Connecting to proxy    url="wss://ec2-18-221-152-110.us-east-2.compute.amazonaws.com:873/v1-k3s/connect"
```
Would love to continue the discussion on how to natively integrate this functionality into K3S

**Comment by bugfest** [comment]
Hi @ndjhartman, I'm glad you find the patch useful. I completely missed @CamelCaseNotation and @erikwilson last comments, sorry guys; and I agree with you, without those improvements my proposal is just a workaround. 

I'm happy to revisit this and make the required changes to comply with those network and functional requirements.

**Comment by iam-TJ** [comment]
I dealt with this issue from the network side by setting up a wireguard VPN between master and each worker so they all sit on the same sub-net (10.127.0.0/16), and used:
```
export INSTALL_K3S_EXEC="--node-external-ip 10.127.0.1"
k3s-install.sh
scp /var/lib/rancher/k3s/server/node-token external00.wg0:/tmp/
```
To ensure the master uses the Wireguard interface's IP address.

On the clients I needed:
```
export K3S_TOKEN="$( cat /tmp/node-token )"
export K3S_URL="https://10.127.0.1:6443"
export K3S_NODE_NAME="external00.k3s"
k3s-install.sh
```
`/etc/hosts` on master and all workers contains entries for each worker of the form:
```
10.127.0.7 external00.k3
```
which matches the IPv4 set on each worker's Wireguard interface.

**Comment by ndjhartman** [comment]
Another option is iptables. I just remap the internal IP of the node to the external:

```
iptables -t nat -A OUTPUT -p tcp -d <INTERNAL_IP> --dport 6443 -j DNAT --to-destination <PUBLIC_IP>:6443
```

This will unfortunately be reset on reboot. Generate a config file for easy reapplication
```
iptables-save > /etc/iptables.conf
```
On reboot,
```
iptables-restore < /etc/iptables.conf
```

**Pull request closed without merging**
