### PR TITLE
support custom containerd config for etc/containerd/config.toml

### PR DESCRIPTION
**Pull request by qxo**
ie:  add private registry mirror
* `export CONTAINERD_CUSTOM_CONFIG="$(cat  containerd_custom.conf)" `

* containerd_custom.conf
```
[plugins.cri.registry.mirrors]
  [plugins.cri.registry.mirrors."docker.io"]
    endpoint = ["https://docker:5000","https://registry-1.docker.io"]
```

### CODE REVIEW

**Comment by uablrek** [comment]
This does the same as https://github.com/rancher/k3s/pull/248 .
Which one will "win"?

**Comment by ibuildthecloud** [comment]
This is becoming a bit more complicated.  I think we need to go towards a template approach for the config.toml.  The issue is that people want to customize it but we also want to provide CLI args that alter it.  In the pipeline line is configuration for registries, katacontainers, root less plus users want fully custom.

So what I propose is that the k3s agent writes a file like config.toml.tmpl that is a golang template to something like `/var/lib/rancher/k3s/agent/containerd/config.toml.tmpl`.  Then a user can supply a file like `/var/lib/rancher/k3s/agent/containerd/config-override.toml.tmpl` that will then be a copy and modification of the base template.

**Comment by xrain0610** [comment]
I think ，make all config with cli is better，I only need to config mirrors，the cli will easy more.

**Comment by xrain0610** [comment]
this feature is very important for china users。the gfw was maked pull image so slowly. this must resolve as soon as possible.

**Comment by galal-hussein** [comment]
Closed in favor of https://github.com/rancher/k3s/pull/381

**Pull request closed without merging**
