### PR TITLE
add tls-sans to api-server cert

### PR DESCRIPTION
**Pull request by KnicKnic**
Add TLS sans to api server cert. This seems to be related to https://github.com/rancher/k3s/issues/1452

### CODE REVIEW

**Comment by brandond** [comment]
This shouldn't be necessary. As far as I can tell, this cert isn't ever used for anything outside the cluster - k3s uses a different cert for the 6443 endpoint that is used for inter-node communication.

**Comment by KnicKnic** [comment]
> This shouldn't be necessary. As far as I can tell, this cert isn't ever used for anything outside the cluster - k3s uses a different cert for the 6443 endpoint that is used for inter-node communication.

@brandond 
When I launch k3s, log state that it is running kube-apiserver with parameters including `--tls-private-key-file=serving-kube-apiserver.key`

This appears to be the code to generate the server-kube-apiserver.key

**Comment by brandond** [comment]
Yes, this controls the certificate that's used for the internal apiserver endpoint. As far as I can tell this is NOT the same endpoint as external clients (kubectl, etc) interact with on port 6443.

**Comment by KnicKnic** [comment]
@brandond 
I see. I confused advertise and secure-port, I probably grabbed an incorrect kubernetes client config file during testing.

The 6443 should already have a SAN see here https://github.com/rancher/k3s/blob/16c8554b5ca6636dbacaf5e00cee31dfea87e622/pkg/cluster/https.go#L40

**Comment by KnicKnic** [comment]
As per above this is not needed.

**Pull request closed without merging**
