### PR TITLE
Upgrade to go v1.13.1

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by chenrui333** [comment]
Right now has issue with 
```
github.com/rancher/k3s/cmd/k3s imports
	github.com/rancher/k3s/pkg/data: cannot find module providing package github.com/rancher/k3s/pkg/data
github.com/rancher/k3s/pkg/ctr imports
	github.com/containerd/containerd/cmd/ctr/app imports
	github.com/containerd/containerd/cmd/ctr/commands/run imports
	github.com/Microsoft/hcsshim/cmd/containerd-shim-runhcs-v1/options: module github.com/Microsoft/hcsshim@latest (v0.8.6) found, but does not contain package github.com/Microsoft/hcsshim/cmd/containerd-shim-runhcs-v1/options
```

**Comment by chenrui333** [comment]
Relates to https://github.com/golang/go/issues/34085

Waiting for golang v1.13.2 for unblocking the PR.

**Comment by chenrui333** [comment]
Looks like this is not an issue in the CI.

**Comment by erikwilson** [comment]
Thanks @chenrui333!

**Comment by chenrui333** [comment]
Thanks for the merge!

**Pull request merged**
