### PR TITLE
containerd: bump to v1.3.4-k3s1

### PR DESCRIPTION
**Pull request by dweomer**
- `go mod edit -replace github.com/containerd/containerd=github.com/rancher/containerd@v1.3.4-k3s1`
- `go mod vendor`
- `go mod tidy`

Addresses #1906

### CODE REVIEW

**Comment by erikwilson** [comment]
Is there any impact with the addition of `NOTIFY_SOCKET` support?

**Comment by dweomer** [comment]
> Is there any impact with the addition of `NOTIFY_SOCKET` support?

My apologies @erikwilson I missed this. Reviewing the changes it looks like, with the way we use containerd, systemd is likely to incur gratuitous notifications and I have no idea how it will act in such a scenario.

**Comment by dweomer** [comment]
@erikwilson looking further into the vendored changes: https://github.com/mxpv/containerd/blob/ddae905b824a264be620cea03d3dee66f779f19a/vendor/github.com/coreos/go-systemd/v22/daemon/sdnotify.go#L56-L71

I do not think this will do anything unless/until k3s leverages notify socket directly (which could be mitigated by eliding the `NOTIFY_SOCKET` envvar when k3s spawns containerd). I can include such a guard with this change.

**Comment by liyimeng** [comment]
nice, will this help for https://github.com/rancher/k3s/issues/1962?

**Comment by dweomer** [comment]
> Nice, will this help for #1962 I hope it bring the bug fix to solve my problem, which is really annoying. I have to reboot the malfunctioning node to get a hold of the cluster again.

@liyimeng hmm, are you thinking about the resource/cleanup changes in containerd 1.3.5? We will need to update our fork to pull those in.

**Comment by liyimeng** [comment]
@dweomer That might be the case. The problem I have is that I run a k3s simple cluster. I did not do much things, but let it run for some weeks. It become unusable. I check into the nodes, and found they have a lot of mounts. run  mount/df/du command takes very lot time to finish. When I give up and decide to restart the nodes, it take half an hour to unmount those overly fs, I lost patience and have to do a hard reset. 

This seem not good for a long running cloud system.

**Comment by brandond** [comment]
@dweomer containerd 1.3.5-k3s1 is available if you want to update this PR for #1962 - all the stuff from 1.3.4-k3s1 rebased cleanly.

**Comment by dweomer** [comment]
> @dweomer containerd 1.3.5-k3s1 is available if you want to update and rebase this PR. All the stuff from 1.3.4-k3s1 rebased cleanly.

After validating that k3s is working with and updated and backported containerd/cri with selinux fixes from master/1.4.x bumping to the latest release of containerd 1.3.x is next.

**Comment by dweomer** [comment]
Superseded by #2065

**Pull request closed without merging**
