### PR TITLE
Add --proxy-mode option to allow user choose ipvs or other proxy mode

### PR DESCRIPTION
**Pull request by vincentmli**
the default is iptables mode if the option is omitted, use --proxy-node ipvs
for ipvs mode

### CODE REVIEW

**Comment by erikwilson** [comment]
Does this already work with a `--kube-proxy-arg proxy-node=ipvs` flag?

**Comment by vincentmli** [comment]
> Does this already work with a `--kube-proxy-arg proxy-node=ipvs` flag?

I just tested with following k3s service
<pre>
ExecStart=/usr/local/bin/k3s server --no-deploy traefik --kube-proxy-arg proxy-mode ipvs --flannel-iface ens224 --node-ip 10.169.72.189
</pre>

or 

<pre>
ExecStart=/usr/local/bin/k3s server --no-deploy traefik --kube-proxy-arg proxy-mode=ipvs --flannel-iface ens224 --node-ip 10.169.72.189
</pre>

both got error 
<pre>
-- Unit k3s.service has begun starting up.
Apr 23 09:20:40 rancher-k3s k3s[2729]: Incorrect Usage: flag provided but not defined: -kube-proxy-arg

</pre>

**Comment by erikwilson** [comment]
What version of k3s are you using? That option became available in 0.4.0: https://github.com/rancher/k3s/releases/tag/v0.4.0

**Comment by vincentmli** [comment]
> What version of k3s are you using? That option became available in 0.4.0: https://github.com/rancher/k3s/releases/tag/v0.4.0

I am running v0.4.0-rc3, no --proxy-mode option exist in v0.4.0. kube-proxy-arg exist, I need  to quote 
as --kube-proxy-arg "proxy-mode=ipvs", and it works now. there is another problem with ipvs mode though, pod will not be able to talk to the cluster service say 10.43.0.1:443 that point to 127.0.0.1:6445, no DNAT applied,  no problem with iptables mode because iptables has nat rule:
<pre>

Chain KUBE-SEP-QUSWRCCKNVSH5RXX (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  127.0.0.1            0.0.0.0/0           
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp to:127.0.0.1:6445
</pre>

I will file it as separate issue

**Pull request closed without merging**
