### PR TITLE
Add Trivy Scans for Built Images

### PR DESCRIPTION
**Pull request by briandowns**
#### Proposed Changes ####

Add a step in the build process to scan a k3s image by Trivvy to detect any security flaws.

#### Linked Issues ####

rancher/k3s#2106

### CODE REVIEW

**Review by galal-hussein — APPROVED** [review]
LGTM

**Comment by briandowns** [comment]
Build currently failing due to rate limiting. :/

**Review by dweomer — APPROVED** [review]

**Comment by brandond** [comment]
does `--quiet` mean that we don't get to see why it's failing?

```
++ trivy --quiet image --severity HIGH,CRITICAL --no-progress --ignore-unfixed rancher/k3s:v1.19.1-k3s-74ce99f5-amd64
--
1234 | time="2020-09-16T20:40:11Z" level=fatal msg="exit status 1"
```

**Comment by briandowns** [comment]
> Does `--quiet` mean that we don't get to see why it's failing?
> 
> ```
> ++ trivy --quiet image --severity HIGH,CRITICAL --no-progress --ignore-unfixed rancher/k3s:v1.19.1-k3s-74ce99f5-amd64
> --
> 1234 | time="2020-09-16T20:40:11Z" level=fatal msg="exit status 1"
> ```

Should just suppress logger output and progress bar. Failures should still be written.

**Comment by brandond** [comment]
I'm not seeing any trivy output at all in the Drone logs. Is it still getting called or am I just searching for the wrong thing?

**Comment by briandowns** [comment]
> I'm not seeing any trivy output at all in the Drone logs. Is it still getting called or am I just searching for the wrong thing?

Line 1470 in the build section of amd64

**Comment by brandond** [comment]
Thanks. For some reason Chrome was having a hard time finding it in a page search.

**Review by brandond — APPROVED** [review]

**Review by dweomer — APPROVED** [review]

**Pull request merged**
