### PR TITLE
Move from jteeuwen/go-bindata to go-bindata/go-bindata

### PR DESCRIPTION
**Pull request by warmchang**
Follow the progress of the upstream kubernetes/kubernetes community.

🔧  jteeuwen/go-bindata --> go-bindata/go-bindata

Fix https://github.com/rancher/k3s/issues/728

### CODE REVIEW

**Comment by warmchang** [comment]
- **./scripts/build & ./scripts/package-cli artifacts:**

```
./bin
├── [   3]  ./bin/bridge -> cni
├── [3.2M]  ./bin/cni
├── [114M]  ./bin/containerd
├── [5.8M]  ./bin/containerd-shim
├── [  10]  ./bin/crictl -> containerd
├── [  10]  ./bin/ctr -> containerd
├── [   3]  ./bin/flannel -> cni
├── [   3]  ./bin/host-local -> cni
├── [ 80M]  ./bin/hyperkube
├── [  10]  ./bin/k3s-agent -> containerd
├── [  10]  ./bin/k3s-server -> containerd
├── [  10]  ./bin/kubectl -> containerd
├── [   3]  ./bin/loopback -> cni
├── [   3]  ./bin/portmap -> cni
└── [8.1M]  ./bin/runc
./dist
└── [4.0K]  ./dist/artifacts
    ├── [ 80M]  ./dist/artifacts/hyperkube
    └── [ 46M]  ./dist/artifacts/k3s
./build
├── [4.0K]  ./build/data
│   └── [ 43M]  ./build/data/a8e186bdeed396f80dbd9bbf83aa8619076103d021efa21efdf5f0955402e147.tgz
├── [4.0K]  ./build/out
│   └── [ 43M]  ./build/out/data.tar.gz
└── [4.0K]  ./build/static
```

- **k3s version:**

```
$ ./dist/artifacts/k3s --help
NAME:
   k3s - Kubernetes, but small and simple

USAGE:
   k3s [global options] command [command options] [arguments...]

VERSION:
   7c5c8b5aeb-dirty (7c5c8b5a)

COMMANDS:
     server   Run management server
     agent    Run node agent
     kubectl  Run kubectl
     crictl   Run crictl
     ctr      Run ctr
     help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --debug        Turn on debug logs
   --help, -h     show help
   --version, -v  print the version
$
$ ./dist/artifacts/k3s --version
k3s version 7c5c8b5aeb-dirty (7c5c8b5a)
$
```

- **test the k3s:**

```
$ rm /usr/local/bin/k3s
$ cp ./dist/artifacts/k3s /usr/local/bin/
$
$ systemctl stop k3s.service
$ systemctl restart k3s.service
$
$ k3s kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5-k3s.1", GitCommit:"52ef54a465650e500182c3836a6d3f88efb6a32e", GitTreeState:"clean", BuildDate:"2019-08-05T18:08+00:00Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5-k3s.1", GitCommit:"52ef54a465650e500182c3836a6d3f88efb6a32e", GitTreeState:"clean", BuildDate:"2019-08-05T18:08+00:00Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"linux/amd64"}
$
$ k3s kubectl get all --all-namespaces
NAMESPACE     NAME                             READY   STATUS      RESTARTS   AGE
kube-system   pod/coredns-b7464766c-hb8bb      1/1     Running     0          16m
kube-system   pod/helm-install-traefik-jqp95   0/1     Completed   0          16m
kube-system   pod/svclb-traefik-z957c          2/2     Running     0          16m
kube-system   pod/traefik-56688c4464-ldlw8     1/1     Running     0          16m

NAMESPACE     NAME                 TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                      AGE
default       service/kubernetes   ClusterIP      10.43.0.1      <none>        443/TCP                      17m
kube-system   service/kube-dns     ClusterIP      10.43.0.10     <none>        53/UDP,53/TCP,9153/TCP       17m
kube-system   service/traefik      LoadBalancer   10.43.34.234   172.17.0.57   80:31588/TCP,443:30282/TCP   16m

NAMESPACE     NAME                           DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
kube-system   daemonset.apps/svclb-traefik   1         1         1       1            1           <none>          16m

NAMESPACE     NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/coredns   1/1     1            1           17m
kube-system   deployment.apps/traefik   1/1     1            1           16m

NAMESPACE     NAME                                 DESIRED   CURRENT   READY   AGE
kube-system   replicaset.apps/coredns-b7464766c    1         1         1       16m
kube-system   replicaset.apps/traefik-56688c4464   1         1         1       16m

NAMESPACE     NAME                             COMPLETIONS   DURATION   AGE
kube-system   job.batch/helm-install-traefik   1/1           20s        17m
$
$ k3s --version
k3s version 7c5c8b5aeb-dirty (7c5c8b5a)
$
```

**Comment by ibuildthecloud** [comment]
Everything looks right, and we should definitely move to go-bindata, but the build is failing for some reason.

**Comment by erikwilson** [comment]
Thanks for the PR @warmchang ! 

Looks like it is failing the porcelain check, the changes to pkg/static/zz_generated_bindata.go from `go generate` should be committed in this PR also.

**Comment by warmchang** [comment]
Thank you for reminder @ibuildthecloud @erikwilson , all ci checks have passed now.


---
BTW:

Actually the commit 7c5c8b5 has included "pkg/static/zz_generated_bindata.go":
https://github.com/rancher/k3s/commit/7c5c8b5aeb07f2f0179189ce2f70202b188e3146#diff-afbdefc260b6a09cebf2c1218c4d0e3c, but the content related to Traefik1640Tgz has been lost.

It seems that you must manually download traefik-1.64.0.tgz to dir "build/static/charts/" and then run "./scripts/package-cli" to make the "pkg/static/zz_generated_bindata.go" correct.

Can these operations be integrated into the ci shell command to run automatically? :smiley:

**Comment by yamt** [comment]
lgtm.

didn't "scripts/download" work?

**Comment by warmchang** [comment]
> lgtm.
> 
> didn't "scripts/download" work?


Ok, the describetion should be "./scripts/download && ./scripts/build && ./scripts/package-cli":

https://github.com/rancher/docs/blame/20ca2f20af99be53ed7501c78ecc5dfe8f0f0755/content/k3s/latest/en/building/_index.md#L19

---
And catch another similar issue in [PR 715](https://github.com/rancher/k3s/pull/715) , lost the chartsTraefik tgz content.

https://github.com/rancher/k3s/pull/715/files?file-filters%5B%5D=.go&file-filters%5B%5D=No+extension#diff-afbdefc260b6a09cebf2c1218c4d0e3cL71-L90

ping @StrongMonkey :smiley:

**Comment by ibuildthecloud** [comment]
LGTM

**Pull request merged**
