### PR TITLE
No longer use basic auth for default admin account

### PR DESCRIPTION
**Pull request by ibuildthecloud**

### CODE REVIEW

**Comment by erikwilson** [comment]
I accidentally had my credentials in a video call, now how do I revoke the cert for my admin account? 🤯🤮☠️

**Comment by brandond** [comment]
With this change, does the kubelet still need ` --basic-auth-file=/var/lib/rancher/k3s/server/cred/passwd`?

**Comment by brandond** [comment]
Oh, I see, it's still used when new servers or agents join the cluster. Looks like the admin password is still in there though, even though admin now uses cert auth.

**Comment by hongkunyoo** [comment]
Is there a plan to add this feature in 1.17.x release? I really want this feature in 1.17.

**Comment by si458** [comment]
just wondering if this was merged to the master branch,
how long before its inserted into k3s?
and will this replace the current user/pass in the `.kube/config`?

**Pull request merged**
