### PR TITLE
Upgrade to go1.12.9 & golang/x/net dependency vendor

### PR DESCRIPTION
**Pull request by warmchang**
Fix: https://github.com/rancher/k3s/issues/700

1. Upgrade to go1.12.8
https://github.com/golang/tools/commits/release-branch.go1.12 has no changes, keep to checkout the aa82965741a9fecd12b026fbb3d3c6ed3231b8f8:
https://github.com/rancher/k3s/blob/b4b7504a7f878e24e706c15dd1ceb844ec595efb/Dockerfile.dapper#L9

2. Upgrade the golang/x/net dependency vendor
https://github.com/rancher/k3s/blob/5d88cc71132cc8631d46a5859048e4fcf0a00c7a/vendor.conf#L75
https://go.googlesource.com/net/+/b3756b4b77d7b13260a0a2ec658753cf48922eac --> https://go.googlesource.com/net/+/cdfb69ac37fc6fa907650654115ebebb3aae2087
and trash to get the new golang/x/net vendor.

### CODE REVIEW

**Comment by warmchang** [comment]
- Build artifacts:

```
./dist
└── [4.0K]  ./dist/artifacts
    ├── [ 80M]  ./dist/artifacts/hyperkube
    ├── [ 40M]  ./dist/artifacts/k3s
    └── [194M]  ./dist/artifacts/k3s-airgap-images-amd64.tar
./build
├── [4.0K]  ./build/data
│   └── [ 43M]  ./build/data/09e1bce1e25ee77a1af21cc490a796f731477959e044dbb120453af8e277e95f.tgz
├── [4.0K]  ./build/out
│   └── [ 37M]  ./build/out/data.tar.gz
└── [4.0K]  ./build/static
    └── [4.0K]  ./build/static/charts
        └── [ 23K]  ./build/static/charts/traefik-1.64.0.tgz

$ ./dist/artifacts/k3s --version
k3s version d53119c62d (d53119c6)
$
```

- Local run:

```
$ ./dist/artifacts/k3s server &
[1] 21723
$ INFO[0000] Preparing data dir /var/lib/rancher/k3s/data/b359f19bd430b4827c740791a01164bb8a6fa7f2f2b770f042bc7d7d5c97bb56
INFO[2019-08-14T09:19:32.375385954Z] Starting k3s d53119c62d (d53119c6)
INFO[2019-08-14T09:19:32.941740976Z] Running kube-apiserver --advertise-port=6443 --allow-privileged=true --api-audiences=unknown --authorization-mode=Node,RBAC --basic-auth-file=/var/lib/rancher/k3s/server/cred/passwd --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --enable-admission-plugins=NodeRestriction --insecure-port=0 --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key--requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=k3s --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-cluster-ip-range=10.43.0.0/16 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key
......

$ ./dist/artifacts/k3s kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5-k3s.1", GitCommit:"52ef54a465650e500182c3836a6d3f88efb6a32e", GitTreeState:"clean", BuildDate:"2019-08-05T18:08+00:00Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5-k3s.1", GitCommit:"52ef54a465650e500182c3836a6d3f88efb6a32e", GitTreeState:"clean", BuildDate:"2019-08-05T18:08+00:00Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}
$
$ ./dist/artifacts/k3s kubectl get all --all-namespaces
NAMESPACE     NAME                             READY   STATUS      RESTARTS   AGE
kube-system   pod/coredns-b7464766c-thjtl      1/1     Running     0          109s
kube-system   pod/helm-install-traefik-wx25m   0/1     Completed   0          109s
kube-system   pod/svclb-traefik-lrncr          2/2     Running     0          79s
kube-system   pod/traefik-56688c4464-5tlrf     1/1     Running     0          79s

NAMESPACE     NAME                 TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                      AGE
default       service/kubernetes   ClusterIP      10.43.0.1      <none>        443/TCP                      2m6s
kube-system   service/kube-dns     ClusterIP      10.43.0.10     <none>        53/UDP,53/TCP,9153/TCP       2m6s
kube-system   service/traefik      LoadBalancer   10.43.67.162   172.17.0.19   80:31214/TCP,443:30041/TCP   79s

NAMESPACE     NAME                           DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
kube-system   daemonset.apps/svclb-traefik   1         1         1       1            1           <none>          79s

NAMESPACE     NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/coredns   1/1     1            1           2m6s
kube-system   deployment.apps/traefik   1/1     1            1           79s

NAMESPACE     NAME                                 DESIRED   CURRENT   READY   AGE
kube-system   replicaset.apps/coredns-b7464766c    1         1         1       109s
kube-system   replicaset.apps/traefik-56688c4464   1         1         1       79s

NAMESPACE     NAME                             COMPLETIONS   DURATION   AGE
kube-system   job.batch/helm-install-traefik   1/1           31s        2m5s
$ ./dist/artifacts/k3s --version
k3s version d53119c62d (d53119c6)
$
```

**Comment by ibuildthecloud** [comment]
Can you bump to 1.12.9? 1.12.8 was a security release and didn't actually include the fix we needed.

**Comment by warmchang** [comment]
> Can you bump to 1.12.9? 1.12.8 was a security release and didn't actually include the fix we needed.

No problem, I will update the commits ASAP.

**Comment by ibuildthecloud** [comment]
I appears the ARM images for golang 1.12.9 don't exist (yet?).

**Comment by warmchang** [comment]
Yes, these images don't exist. Waiting for the official release.

https://hub.docker.com/r/arm64v8/golang/tags
https://hub.docker.com/r/arm32v7/golang/tags

```
$ docker pull arm64v8/golang:1.12.8-alpine3.9
1.12.8-alpine3.9: Pulling from arm64v8/golang
0362ad1dd800: Pull complete
4add8f29bf03: Pull complete
d2a54cdb6f8d: Pull complete
373b04180a74: Pull complete
57e1fda8a78c: Pull complete
Digest: sha256:b140b93e7967a6027375b13ceefde583c1fdb8a95dc9bb72439e5241c135937b
Status: Downloaded newer image for arm64v8/golang:1.12.8-alpine3.9
$
$ docker pull arm64v8/golang:1.12.9-alpine3.9
Error response from daemon: manifest for arm64v8/golang:1.12.9-alpine3.9 not found
$
$ docker pull arm32v7/golang:1.12.8-alpine3.9
1.12.8-alpine3.9: Pulling from arm32v7/golang
856f4240f8db: Pull complete
244bb6187057: Pull complete
f644f99f22ce: Pull complete
8c128ca8ec41: Pull complete
31cf29e2fa9d: Pull complete
Digest: sha256:bb7c7c059747a883a88b501b773d4f7817463eac188c771831cf807a796ee4d9
Status: Downloaded newer image for arm32v7/golang:1.12.8-alpine3.9
$
$ docker pull arm32v7/golang:1.12.9-alpine3.9
Error response from daemon: manifest for arm32v7/golang:1.12.9-alpine3.9 not found
$
```

**Comment by erikwilson** [comment]
Looks like it should be working, https://github.com/docker-library/golang/blob/2f6469ffe955721dd25e4cbb3013506659998aad/1.12/alpine3.9/Dockerfile, even though not showing up in tags and can't pull it is listed under 'simple tags' https://hub.docker.com/r/arm64v8/golang. amd64 build is also throwing an interesting error now. 

Would it be worth decoupling the alpine & golang stuff, and just install golang separately?

**Comment by erikwilson** [comment]
Looks like the arm builds for docker golang have been failing since Aug 14th w/ issues checking out the repo:
https://doi-janky.infosiftr.net/job/multiarch/job/arm32v6/job/golang/
https://doi-janky.infosiftr.net/job/multiarch/job/arm64v8/job/golang/

**Comment by warmchang** [comment]
Replace alpine requires to change the package management system in "Dockerfile.dapper".
Deal with it tomorrow. (My time zone is UTC+8 ...)

```
RUN apk -U --no-cache add bash git gcc musl-dev docker vim less file curl wget ca-certificates jq linux-headers zlib-dev tar zip squashfs-tools npm coreutils \
    python3 py3-pip python3-dev openssl-dev libffi-dev libseccomp libseccomp-dev make
RUN pip3 install 'tox==3.6.0'
RUN apk -U --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/main/ add sqlite-dev sqlite-static

```

**Comment by ibuildthecloud** [comment]
I opened an issue upstream to hopefully fix the alpine ARM images. https://github.com/docker-library/official-images/issues/6490

**Comment by warmchang** [comment]
> I opened an issue upstream to hopefully fix the alpine ARM images. [docker-library/official-images#6490](https://github.com/docker-library/official-images/issues/6490)

Thanks @ibuildthecloud , CI has successful. PTAL.

**Comment by ibuildthecloud** [comment]
@warmchang Thanks for sticking with this one.

**Pull request merged**
