### PR TITLE
Use channel server for install script

### PR DESCRIPTION
**Pull request by erikwilson**
For #1578

### CODE REVIEW

**Comment by erikwilson** [comment]
Needs needs v1.17.4 moved to stable before merge.

**Comment by ibuildthecloud** [comment]
Looks good. Obviously can't merge until we move channels.yaml to this repo.

**Comment by erikwilson** [comment]
@ShylajaDevadiga for testing can use 
```bash
curl https://raw.githubusercontent.com/rancher/k3s/dddbd16305284ae4bd14c0aade892412310d7edc/install.sh | INSTALL_K3S_CHANNEL=v1.16 sh -
```

Where `INSTALL_K3S_CHANNEL` is `stable` if not defined, and a list of all available channels can be found with `curl -s https://update.k3s.io/v1-release/channels | jq -r '.data[] | .id'`

**Comment by ShylajaDevadiga** [comment]
@erikwilson I have verified creating cluster using channel server in install script setting INSTALL_K3S_CHANNEL=stable as well as INSTALL_K3S_CHANNEL=v1.16 and upgrading to stable (v.1.17.4+k3s1)

**Pull request merged**
