### PR TITLE
Update flannel to v0.12.0-k3s1

### PR DESCRIPTION
**Pull request by erikwilson**

### CODE REVIEW

**Comment by brandond** [comment]
How much larger does pulling in the AWS SDK make the binary?

**Comment by erikwilson** [comment]
Where is it pulling in the aws sdk? 

I see a that go modules had examined an older version of the library, probably do to flannel being changed to use go modules instead of glide, but it looks like the vendored aws sdk or the use of it has not actually changed. 

This update should not have an appreciable difference on the file size, we should probably report the file size as part of the build process tho.

**Comment by brandond** [comment]
Right you are - I was on mobile and it looked like it was actually pulling in the sdk, but I see now that's not the case. My apologies.

**Comment by brandond** [comment]
@erikwilson I just rebased this. Trying to get some of these aging version-bump PRs cleared through.

**Pull request merged**
