### PR TITLE
Add support for compressed images when pre-loading images

### PR DESCRIPTION
**Pull request by fkautz**
Image preloading now supports compressed images in the following formats:

* bzip2
* gzip
*  lz4

Addresses #2145

### CODE REVIEW

**Comment by fkautz** [comment]
This still needs to be tested. Does anyone have any recommendations on the most effective way to automate testing this feature?

**Comment by fkautz** [comment]
I'm not sure why, drone did not update the PR's build. The build is currently passing.

https://drone-pr.rancher.io/rancher/k3s/2974

**Comment by dweomer** [comment]
I don't see a change for `github.com/google/google-cmp` package in `go.{mod,sum}` but there are new files under `vendor/`?

**Comment by cjellick** [comment]
Hi @fkautz. Thanks for the pr. We’ll take a look soon. We are pretty tied up with a handful of tasks, so it might be end of week before we can take a look.

**Comment by cjellick** [comment]
Unless @dweomer is looking now :-)

**Comment by dweomer** [comment]
> I don't see a change for `github.com/google/google-cmp` package in `go.{mod,sum}` but there are new files under `vendor/`?

Wait, I see it: https://github.com/rancher/k3s/pull/2165/files#diff-f949e2d81c8076ebbf8af38fcbb72c1fR371-R372
Disregard.

**Comment by dweomer** [comment]
> Unless @dweomer is looking now :-)

This addresses #2145. I would like to do some testing with this but as @cjellick mentioned I have a couple of other priorities to knock down first.

**Comment by fkautz** [comment]
I tested with 4 valid images and verified that they were present in the container:

```
/ # ls -lha /var/lib/rancher/k3s/agent/images/
total 346M
drwxr-xr-x 6 0 0  192 Aug 27 03:37 .
drwxr-xr-x 6 0 0 4.0K Aug 27 03:37 ..
-rw-r--r-- 1 0 0 2.6M Aug 27 03:04 alpine.tar.gz
-rw-r--r-- 1 0 0 213M Aug 27 03:37 centos.tar
-rw-r--r-- 1 0 0  83M Aug 27 03:24 fedora.tar.lz4
-rw-r--r-- 1 0 0  23M Aug 27 03:25 ubuntu.tar.bz2
/ # crictl images
IMAGE                                      TAG                 IMAGE ID            SIZE
docker.io/library/alpine                   3.12                a24bb4013296f       5.85MB
docker.io/library/alpine                   latest              a24bb4013296f       5.85MB
docker.io/library/centos                   latest              0d120b6ccaa8c       222MB
docker.io/library/fedora                   latest              a368cbcfa6789       189MB
docker.io/library/ubuntu                   latest              4e2eef94cd6b9       76.3MB
```

I also tested an invalid image and saw an appropriate error message.

**Pull request merged**
