### PR TITLE
Fix panic in node controller

### PR DESCRIPTION
**Pull request by erikwilson**
For #712

### CODE REVIEW

**Comment by yamt** [comment]
what panic does this fix?

**Comment by erikwilson** [comment]
From the logs in the linked issue:
```
fatal error: concurrent map writes

goroutine 8311 [running]:
runtime.throw(0x343f8c6, 0x15)
	/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc003ba8830 sp=0xc003ba8800 pc=0x42f0a2
runtime.mapassign_faststr(0x2ee7f80, 0xc002959260, 0x341db2a, 0x9, 0xa)
	/usr/local/go/src/runtime/map_faststr.go:291 +0x40f fp=0xc003ba8898 sp=0xc003ba8830 pc=0x41471f
github.com/rancher/k3s/pkg/node.(*handler).updateHosts(0xc003c834c0, 0xc0035a6000, 0x20300100000000, 0xc004cf7ce0, 0x7feb05e58050, 0x16000c003629c80)
	/go/src/github.com/rancher/k3s/pkg/node/controller.go:94 +0x374 fp=0xc003ba8b78 sp=0xc003ba8898 pc=0x2733bc4
github.com/rancher/k3s/pkg/node.(*handler).onChange(...)
	/go/src/github.com/rancher/k3s/pkg/node/controller.go:33
github.com/rancher/k3s/pkg/node.(*handler).onChange-fm(0xc0021e59c0, 0x18, 0xc0035a6000, 0x0, 0x45bf07, 0x8)
	/go/src/github.com/rancher/k3s/pkg/node/controller.go:29 +0x5e fp=0xc003ba8bb8 sp=0xc003ba8b78 pc=0x273431e
```

**Comment by yamt** [comment]
lgtm. i don't understand who could be the concurrent writer though.

**Comment by erikwilson** [comment]
I abbreviated the log, but the original file contains two important pieces, at the start of the panic:
```
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 8311 [running]:
runtime.throw(0x343f8c6, 0x15)
	/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc003ba8830 sp=0xc003ba8800 pc=0x42f0a2
runtime.mapassign_faststr(0x2ee7f80, 0xc002959260, 0x341db2a, 0x9, 0xa)
	/usr/local/go/src/runtime/map_faststr.go:291 +0x40f fp=0xc003ba8898 sp=0xc003ba8830 pc=0x41471f
github.com/rancher/k3s/pkg/node.(*handler).updateHosts(0xc003c834c0, 0xc0035a6000, 0x20300100000000, 0xc004cf7ce0, 0x7feb05e58050, 0x16000c003629c80)
	/go/src/github.com/rancher/k3s/pkg/node/controller.go:94 +0x374 fp=0xc003ba8b78 sp=0xc003ba8898 pc=0x2733bc4
github.com/rancher/k3s/pkg/node.(*handler).onChange(...)
	/go/src/github.com/rancher/k3s/pkg/node/controller.go:33
github.com/rancher/k3s/pkg/node.(*handler).onChange-fm(0xc0021e59c0, 0x18, 0xc0035a6000, 0x0, 0x45bf07, 0x8)
	/go/src/github.com/rancher/k3s/pkg/node/controller.go:29 +0x5e fp=0xc003ba8bb8 sp=0xc003ba8b78 pc=0x273431e
github.com/rancher/k3s/vendor/github.com/rancher/wrangler-api/pkg/generated/controllers/core/v1.FromNodeHandlerToHandler.func1(0xc0021e59c0, 0x18, 0x3be47c0, 0xc0035a6000, 0x203000, 0x203000, 0x18, 0xc00352c478)
	/go/src/github.com/rancher/k3s/vendor/github.com/rancher/wrangler-api/pkg/generated/controllers/core/v1/node.go:102 +0x65 fp=0xc003ba8bf8 sp=0xc003ba8bb8 pc=0x26f9cf5
github.com/rancher/k3s/vendor/github.com/rancher/wrangler/pkg/generic.(*Handlers).Handle(0xc003c835c0, 0xc0021e59c0, 0x18, 0x3be47c0, 0xc0035a6000, 0x2fc5680, 0x33e98c0, 0xc0035a6000, 0x3be47c0)
	/go/src/github.com/rancher/k3s/vendor/github.com/rancher/wrangler/pkg/generic/handlers.go:26 +0x100 fp=0xc003ba8cb0 sp=0xc003ba8bf8 pc=0x26cf320
github.com/rancher/k3s/vendor/github.com/rancher/wrangler/pkg/generic.(*Handlers).Handle-fm(0xc0021e59c0, 0x18, 0x3be47c0, 0xc0035a6000, 0xc0035a6000, 0xc00352c501, 0x0, 0x0)
	/go/src/github.com/rancher/k3s/vendor/github.com/rancher/wrangler/pkg/generic/handlers.go:20 +0x52 fp=0xc003ba8d08 sp=0xc003ba8cb0 pc=0x26d0c62
github.com/rancher/k3s/vendor/github.com/rancher/wrangler/pkg/generic.(*Controller).syncHandler(0xc001982480, 0xc0021e59c0, 0x18, 0x2e1b120, 0xc0039d59a0)
	/go/src/github.com/rancher/k3s/vendor/github.com/rancher/wrangler/pkg/generic/controller.go:157 +0xdb fp=0xc003ba8d58 sp=0xc003ba8d08 pc=0x26cdaab
github.com/rancher/k3s/vendor/github.com/rancher/wrangler/pkg/generic.(*Controller).processSingleItem(0xc001982480, 0x2e1b120, 0xc0039d59a0, 0x0, 0x0)
	/go/src/github.com/rancher/k3s/vendor/github.com/rancher/wrangler/pkg/generic/controller.go:138 +0xda fp=0xc003ba8e28 sp=0xc003ba8d58 pc=0x26cd66a
github.com/rancher/k3s/vendor/github.com/rancher/wrangler/pkg/generic.(*Controller).processNextWorkItem(0xc001982480, 0xc0028823f0)
	/go/src/github.com/rancher/k3s/vendor/github.com/rancher/wrangler/pkg/generic/controller.go:115 +0x51 fp=0xc003ba8e70 sp=0xc003ba8e28 pc=0x26cd4e1
github.com/rancher/k3s/vendor/github.com/rancher/wrangler/pkg/generic.(*Controller).runWorker(0xc001982480)
	/go/src/github.com/rancher/k3s/vendor/github.com/rancher/wrangler/pkg/generic/controller.go:104 +0x2b fp=0xc003ba8e90 sp=0xc003ba8e70 pc=0x26cd46b
github.com/rancher/k3s/vendor/github.com/rancher/wrangler/pkg/generic.(*Controller).runWorker-fm()
	/go/src/github.com/rancher/k3s/vendor/github.com/rancher/wrangler/pkg/generic/controller.go:103 +0x2a fp=0xc003ba8ea8 sp=0xc003ba8e90 pc=0x26d0bfa
github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc003209a40)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54 fp=0xc003ba8ee0 sp=0xc003ba8ea8 pc=0x11f0544
github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc003209a40, 0x3b9aca00, 0x0, 0x1, 0xc002bbeb40)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8 fp=0xc003ba8f90 sp=0xc003ba8ee0 pc=0x11ef818
github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc003209a40, 0x3b9aca00, 0xc002bbeb40)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d fp=0xc003ba8fc8 sp=0xc003ba8f90 pc=0x11ef70d
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc003ba8fd0 sp=0xc003ba8fc8 pc=0x45ead1
created by github.com/rancher/k3s/vendor/github.com/rancher/wrangler/pkg/generic.(*Controller).run
	/go/src/github.com/rancher/k3s/vendor/github.com/rancher/wrangler/pkg/generic/controller.go:86 +0x131
```
And at the end:
```
goroutine 8307 [running]:
runtime.throw(0x343f8c6, 0x15)
	/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc003ac9830 sp=0xc003ac9800 pc=0x42f0a2
runtime.mapassign_faststr(0x2ee7f80, 0xc002959260, 0x341db2a, 0x9, 0xa)
	/usr/local/go/src/runtime/map_faststr.go:291 +0x40f fp=0xc003ac9898 sp=0xc003ac9830 pc=0x41471f
github.com/rancher/k3s/pkg/node.(*handler).updateHosts(0xc003c834c0, 0xc003fd3080, 0xc0025ef600, 0x1, 0xc003e9fbe0, 0x40ec91)
	/go/src/github.com/rancher/k3s/pkg/node/controller.go:94 +0x374 fp=0xc003ac9b78 sp=0xc003ac9898 pc=0x2733bc4
github.com/rancher/k3s/pkg/node.(*handler).onChange(...)
	/go/src/github.com/rancher/k3s/pkg/node/controller.go:33
github.com/rancher/k3s/pkg/node.(*handler).onChange-fm(0xc002f8d0e0, 0x18, 0xc003fd3080, 0x2bfa590, 0x1421f946719a56a1, 0xc003e9fc38)
	/go/src/github.com/rancher/k3s/pkg/node/controller.go:29 +0x5e fp=0xc003ac9bb8 sp=0xc003ac9b78 pc=0x273431e
github.com/rancher/k3s/vendor/github.com/rancher/wrangler-api/pkg/generated/controllers/core/v1.FromNodeHandlerToHandler.func1(0xc002f8d0e0, 0x18, 0x3be47c0, 0xc003fd3080, 0xc0021e59c0, 0xc002f8d0e0, 0x18, 0xc003e9fc78)
	/go/src/github.com/rancher/k3s/vendor/github.com/rancher/wrangler-api/pkg/generated/controllers/core/v1/node.go:102 +0x65 fp=0xc003ac9bf8 sp=0xc003ac9bb8 pc=0x26f9cf5
github.com/rancher/k3s/vendor/github.com/rancher/wrangler/pkg/generic.(*Handlers).Handle(0xc003c835c0, 0xc002f8d0e0, 0x18, 0x3be47c0, 0xc003fd3080, 0x2fc5680, 0x33e98c0, 0xc003fd3000, 0x3be47c0)
	/go/src/github.com/rancher/k3s/vendor/github.com/rancher/wrangler/pkg/generic/handlers.go:26 +0x100 fp=0xc003ac9cb0 sp=0xc003ac9bf8 pc=0x26cf320
github.com/rancher/k3s/vendor/github.com/rancher/wrangler/pkg/generic.(*Handlers).Handle-fm(0xc002f8d0e0, 0x18, 0x3be47c0, 0xc003fd3080, 0xc003fd3080, 0xc003e9fd01, 0x0, 0x0)
	/go/src/github.com/rancher/k3s/vendor/github.com/rancher/wrangler/pkg/generic/handlers.go:20 +0x52 fp=0xc003ac9d08 sp=0xc003ac9cb0 pc=0x26d0c62
github.com/rancher/k3s/vendor/github.com/rancher/wrangler/pkg/generic.(*Controller).syncHandler(0xc001982480, 0xc002f8d0e0, 0x18, 0x2e1b120, 0xc001bd4ae0)
	/go/src/github.com/rancher/k3s/vendor/github.com/rancher/wrangler/pkg/generic/controller.go:157 +0xdb fp=0xc003ac9d58 sp=0xc003ac9d08 pc=0x26cdaab
github.com/rancher/k3s/vendor/github.com/rancher/wrangler/pkg/generic.(*Controller).processSingleItem(0xc001982480, 0x2e1b120, 0xc001bd4ae0, 0x0, 0x0)
	/go/src/github.com/rancher/k3s/vendor/github.com/rancher/wrangler/pkg/generic/controller.go:138 +0xda fp=0xc003ac9e28 sp=0xc003ac9d58 pc=0x26cd66a
github.com/rancher/k3s/vendor/github.com/rancher/wrangler/pkg/generic.(*Controller).processNextWorkItem(0xc001982480, 0xc0033593e0)
	/go/src/github.com/rancher/k3s/vendor/github.com/rancher/wrangler/pkg/generic/controller.go:115 +0x51 fp=0xc003ac9e70 sp=0xc003ac9e28 pc=0x26cd4e1
github.com/rancher/k3s/vendor/github.com/rancher/wrangler/pkg/generic.(*Controller).runWorker(0xc001982480)
	/go/src/github.com/rancher/k3s/vendor/github.com/rancher/wrangler/pkg/generic/controller.go:104 +0x2b fp=0xc003ac9e90 sp=0xc003ac9e70 pc=0x26cd46b
github.com/rancher/k3s/vendor/github.com/rancher/wrangler/pkg/generic.(*Controller).runWorker-fm()
	/go/src/github.com/rancher/k3s/vendor/github.com/rancher/wrangler/pkg/generic/controller.go:103 +0x2a fp=0xc003ac9ea8 sp=0xc003ac9e90 pc=0x26d0bfa
github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc003209a00)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54 fp=0xc003ac9ee0 sp=0xc003ac9ea8 pc=0x11f0544
github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc003209a00, 0x3b9aca00, 0x0, 0x1, 0xc002bbeb40)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8 fp=0xc003ac9f90 sp=0xc003ac9ee0 pc=0x11ef818
github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc003209a00, 0x3b9aca00, 0xc002bbeb40)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d fp=0xc003ac9fc8 sp=0xc003ac9f90 pc=0x11ef70d
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc003ac9fd0 sp=0xc003ac9fc8 pc=0x45ead1
created by github.com/rancher/k3s/vendor/github.com/rancher/wrangler/pkg/generic.(*Controller).run
	/go/src/github.com/rancher/k3s/vendor/github.com/rancher/wrangler/pkg/generic/controller.go:86 +0x131
```

Multiple node change events are triggering multiple onChange functions at almost the same time, and the same configMap is retrieved from cache and modified. The cache objects should not be modified without copying first. If the multi-node onChange is triggered using a copy one or more of the onChange events should fail on update and would retry using an updated configMap from cache.

**Comment by yamt** [comment]
@erikwilson thank you for explanation. it makes sense.

**Pull request merged**
