### PR TITLE
coredns: Add readinessProbe

### PR DESCRIPTION
**Pull request by mrueg**
This adds a readinessProbe using the coredns' ready plugin https://coredns.io/plugins/ready/

### CODE REVIEW

**Comment by mrueg** [comment]
@erikwilson can you help me out here why CI is failing?

**Comment by erikwilson** [comment]
Thanks for the PR @mrueg!

The `pkg/deploy/zz_generated_bindata.go` file needs to be updated & committed after running `go generate`.

I can see a readiness probe being useful for some situations, are you able to describe a little bit about how you plan to use the endpoint?

**Comment by mrueg** [comment]
Thanks, I missed that, will push it.
The endpoint is used in kubernetes/k3s - https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/ and will only allow traffic to get routed to a coredns pod when the pod is actually ready. This helps if you run multiple coredns pods or want to upgrade the coredns deployment.

**Comment by erikwilson** [comment]
Thanks!

**Pull request merged**
