### PR TITLE
Flannel hostgw support

### PR DESCRIPTION
**Pull request by segator**
Now k3s support flannel with hostgw configuration

```
k3s server --flannel-backend hostgw
```

### CODE REVIEW

**Comment by segator** [comment]
Can someone explain me why is failling for ARM?

**Comment by erikwilson** [comment]
Sorry, ARM builds are pretty flakey. There is some 32-bit issue we need to get to the bottom of, and some builds consistently trigger panics that are unrelated to the code being changed.

**Comment by segator** [comment]
Can we integrate?

**Comment by segator** [comment]
what we need to integrate this change?

**Comment by segator** [comment]
sorry to bother you but what we need to integrate this? this is a very simple change

**Comment by erikwilson** [comment]
When I can merge without causing ARM issues.

**Comment by segator** [comment]
How Can I help with the ARM issue? you are not accepting any PR because of that?

**Comment by erikwilson** [comment]
For whatever reason it looks like rebasing fixed the ARM issue, so I am expecting to merge it soon, hopefully within a week. Thanks for your patience!

**Comment by erikwilson** [comment]
Thanks for the PR and your patience @segator!

**Pull request merged**
