### PR TITLE
build: golang 1.14 on alpine 3.12

### PR DESCRIPTION
**Pull request by dweomer**
- golang 1.14.4
- `go mod tidy`
- golangci-lint 1.27.0 (better output, doesn't crash with go 1.14)
- add zlib-static as build-time dependency

### CODE REVIEW

**Comment by brandond** [comment]
Ref:
https://github.com/go-gitea/gitea/issues/11620#issuecomment-633695042
https://github.com/golang/go/issues/38033

**Comment by cjellick** [comment]
Thansk for the heads up @AkihiroSuda

**Comment by dweomer** [comment]
I had forgotten why I was avoiding go 1.14 https://golang.org/doc/go1.14#runtime. Thanks for reminding me @AkihiroSuda

**Comment by warmchang** [comment]
The k/k upstream is dealing with this problem:
[WIP] Update Golang to v1.14.4 https://github.com/kubernetes/kubernetes/pull/88638

**Pull request closed without merging**
